spring.application.name=backend
spring.datasource.url=jdbc:mariadb://mariadb:3306/cutpark
spring.datasource.username=root
spring.datasource.password=snlo2001
spring.jpa.hibernate.ddl-auto=update

jwt.secret=3b73f3d1523b666633a86fb8cb7eb890ead93d4c3f383910203cc351412cbe1f

spring.security.oauth2.client.registration.google.client-id=90897507006-ug17foqaippakpmo01ajvdf8n8cnlipd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
